package com.instrumental.attachment;

enum TonePreset {
    GUITAR_CLEAN_BOOST(0, InstrumentMode.ELECTRIC_GUITAR, "Clean Boost", "Transparent level lift", -1, "Clean"),
    GUITAR_TS808(1, InstrumentMode.ELECTRIC_GUITAR, "Vintage Tube Drive", "Legendary mid-hump overdrive", -1, "Overdrive"),
    GUITAR_TS9(1, InstrumentMode.ELECTRIC_GUITAR, "Bright Tube Drive", "Bright mid-boost overdrive", -1, "Overdrive"),
    GUITAR_KLON(1, InstrumentMode.ELECTRIC_GUITAR, "Transparent Boost", "Transparent god drive", -1, "Overdrive"),
    GUITAR_BD2(1, InstrumentMode.ELECTRIC_GUITAR, "Blues Drive", "Amp-like breakup", -1, "Overdrive"),
    GUITAR_ODR1(1, InstrumentMode.ELECTRIC_GUITAR, "Natural Drive", "Nashville clean drive", -1, "Overdrive"),
    GUITAR_OCD(1, InstrumentMode.ELECTRIC_GUITAR, "Open Drive", "Open dynamic drive", -1, "Overdrive"),
    GUITAR_RAT(2, InstrumentMode.ELECTRIC_GUITAR, "Rodent Distortion", "Classic gritty distortion", -1, "Distortion"),
    GUITAR_DS1(2, InstrumentMode.ELECTRIC_GUITAR, "Orange Distortion", "Orange-box distortion", -1, "Distortion"),
    GUITAR_DPLUS(2, InstrumentMode.ELECTRIC_GUITAR, "Vintage Distortion", "Vintage hard-clip crunch", -1, "Distortion"),
    GUITAR_RIOT(2, InstrumentMode.ELECTRIC_GUITAR, "Tight Modern Distortion", "Modern high-gain distortion", -1, "Distortion"),
    GUITAR_PUGILIST(2, InstrumentMode.ELECTRIC_GUITAR, "Dual Stage Distortion", "Dual-gain distortion", -1, "Distortion"),
    GUITAR_BIG_MUFF(4, InstrumentMode.ELECTRIC_GUITAR, "Wall Fuzz", "Wall-of-sustain fuzz", -1, "Fuzz"),
    GUITAR_FUZZ_FACE(4, InstrumentMode.ELECTRIC_GUITAR, "Germanium Fuzz", "Vintage germanium fuzz", -1, "Fuzz"),
    GUITAR_TONE_BENDER(4, InstrumentMode.ELECTRIC_GUITAR, "Sixties Fuzz", "British 60s fuzz", -1, "Fuzz"),
    GUITAR_METAL_ZONE(3, InstrumentMode.ELECTRIC_GUITAR, "Scooped Metal", "Scooped high-gain metal", -1, "Metal"),
    GUITAR_BEOD(3, InstrumentMode.ELECTRIC_GUITAR, "Hot-Rod Metal", "Hot-rodded amp metal", -1, "Metal"),
    GUITAR_REVV_G3(7, InstrumentMode.ELECTRIC_GUITAR, "Tight High-Gain", "Tight modern high-gain", -1, "Hard Metal"),
    GUITAR_5150(7, InstrumentMode.ELECTRIC_GUITAR, "Brown Sound Drive", "Brown-sound saturation", -1, "Hard Metal"),
    GUITAR_METAL_CORE(7, InstrumentMode.ELECTRIC_GUITAR, "Extreme Metal", "Brutal extreme gain", -1, "Hard Metal"),
    GUITAR_THROTTLE(7, InstrumentMode.ELECTRIC_GUITAR, "Modern Crush", "Chunky modern crush", -1, "Hard Metal"),
    GUITAR_GT_CLEAN(8, InstrumentMode.ELECTRIC_GUITAR, "Studio Natural Clean", "Studio clean + comp", -1, "GT-Style Multi-FX"),
    GUITAR_GT_CRUNCH(9, InstrumentMode.ELECTRIC_GUITAR, "X-Crunch", "Tight touch-sensitive crunch", -1, "GT-Style Multi-FX"),
    GUITAR_GT_BROWN(30, InstrumentMode.ELECTRIC_GUITAR, "Brown Stack", "Hot-rodded brown sound", -1, "GT-Style Multi-FX"),
    GUITAR_GT_LEAD(31, InstrumentMode.ELECTRIC_GUITAR, "X-Lead", "Singing sustain lead", -1, "GT-Style Multi-FX"),
    // Complete GT-1000 factory patch list (Roland Sound List rev 04),
    // each mapped to the closest native amp chain.
    GT_P01_1(1, InstrumentMode.ELECTRIC_GUITAR, "P01-1 PREMIUM DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P01_2(6, InstrumentMode.ELECTRIC_GUITAR, "P01-2 DEEP SHIMMER REV", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P01_3(1, InstrumentMode.ELECTRIC_GUITAR, "P01-3 THE POWER OF MDP", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P01_4(31, InstrumentMode.ELECTRIC_GUITAR, "P01-4 MODERN LD-CL", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P01_5(9, InstrumentMode.ELECTRIC_GUITAR, "P01-5 MULTIBAND CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P02_1(6, InstrumentMode.ELECTRIC_GUITAR, "P02-1 3D JAZZ CHORUS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P02_2(4, InstrumentMode.ELECTRIC_GUITAR, "P02-2 FUZZ LEAD", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P02_3(2, InstrumentMode.ELECTRIC_GUITAR, "P02-3 RECT 57 SL PN TW", "Multi-FX factory · distortion voicing", -1, "GT-Style Multi-FX"),
    GT_P02_4(9, InstrumentMode.ELECTRIC_GUITAR, "P02-4 COUNTRY TWANG", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P02_5(6, InstrumentMode.ELECTRIC_GUITAR, "P02-5 GUITAR PAD 01", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P03_1(6, InstrumentMode.ELECTRIC_GUITAR, "P03-1 ROTATOR", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P03_2(8, InstrumentMode.ELECTRIC_GUITAR, "P03-2 CLEAN & AG MIX", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P03_3(30, InstrumentMode.ELECTRIC_GUITAR, "P03-3 BURNING PURPLE", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P03_4(1, InstrumentMode.ELECTRIC_GUITAR, "P03-4 PHAT GAINER", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P03_5(6, InstrumentMode.ELECTRIC_GUITAR, "P03-5 MILD ORGAN SPACE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P04_1(9, InstrumentMode.ELECTRIC_GUITAR, "P04-1 DIAMOND/CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P04_2(1, InstrumentMode.ELECTRIC_GUITAR, "P04-2 PEDAL POWER", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P04_3(6, InstrumentMode.ELECTRIC_GUITAR, "P04-3 PATTERN DELAY X", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P04_4(1, InstrumentMode.ELECTRIC_GUITAR, "P04-4 SINGLE COIL AC", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P04_5(6, InstrumentMode.ELECTRIC_GUITAR, "P04-5 CRYSTAL CLOUDS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P05_1(6, InstrumentMode.ELECTRIC_GUITAR, "P05-1 TREMOLO REVERB", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P05_2(8, InstrumentMode.ELECTRIC_GUITAR, "P05-2 JAZZ HOLLOW", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P05_3(1, InstrumentMode.ELECTRIC_GUITAR, "P05-3 DRY X-DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P05_4(8, InstrumentMode.ELECTRIC_GUITAR, "P05-4 BASS+GUITAR MIX", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P05_5(1, InstrumentMode.ELECTRIC_GUITAR, "P05-5 FOOT VOL DRV CTL", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P06_1(9, InstrumentMode.ELECTRIC_GUITAR, "P06-1 SIMPLE TWEED 87", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P06_2(1, InstrumentMode.ELECTRIC_GUITAR, "P06-2 DOUBLE AMP", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P06_3(8, InstrumentMode.ELECTRIC_GUITAR, "P06-3 CLEAN CHO/DLY", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P06_4(8, InstrumentMode.ELECTRIC_GUITAR, "P06-4 12 STRUNG", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P06_5(31, InstrumentMode.ELECTRIC_GUITAR, "P06-5 SHRED LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P07_1(9, InstrumentMode.ELECTRIC_GUITAR, "P07-1 CRUNCHED", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P07_2(31, InstrumentMode.ELECTRIC_GUITAR, "P07-2 CTL2:WARP LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P07_3(31, InstrumentMode.ELECTRIC_GUITAR, "P07-3 JUGGER FLAT LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P07_4(30, InstrumentMode.ELECTRIC_GUITAR, "P07-4 BRIT ROCK 1978", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P07_5(8, InstrumentMode.ELECTRIC_GUITAR, "P07-5 CLEAN COMBO", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P08_1(1, InstrumentMode.ELECTRIC_GUITAR, "P08-1 DRIVEN DELUXE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P08_2(8, InstrumentMode.ELECTRIC_GUITAR, "P08-2 MS CLEAN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P08_3(8, InstrumentMode.ELECTRIC_GUITAR, "P08-3 RICH ACOUSTIC", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P08_4(6, InstrumentMode.ELECTRIC_GUITAR, "P08-4 TWO SPEED TREM", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P08_5(1, InstrumentMode.ELECTRIC_GUITAR, "P08-5 BOOSTED X", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P09_1(4, InstrumentMode.ELECTRIC_GUITAR, "P09-1 OCTFUZZ LEAD", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P09_2(9, InstrumentMode.ELECTRIC_GUITAR, "P09-2 EXPERIENCE BLUES", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P09_3(9, InstrumentMode.ELECTRIC_GUITAR, "P09-3 BRITISH CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P09_4(9, InstrumentMode.ELECTRIC_GUITAR, "P09-4 FUNKY RHYTHM", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P09_5(1, InstrumentMode.ELECTRIC_GUITAR, "P09-5 LOW AND DIRTY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P10_1(5, InstrumentMode.ELECTRIC_GUITAR, "P10-1 WAH SOLO", "Multi-FX factory · wah filter voicing", -1, "GT-Style Multi-FX"),
    GT_P10_2(31, InstrumentMode.ELECTRIC_GUITAR, "P10-2 FUSION LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P10_3(6, InstrumentMode.ELECTRIC_GUITAR, "P10-3 OVERTONES", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P10_4(31, InstrumentMode.ELECTRIC_GUITAR, "P10-4 MONO SYNTH LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P10_5(1, InstrumentMode.ELECTRIC_GUITAR, "P10-5 STRAY CUTZ", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P11_1(6, InstrumentMode.ELECTRIC_GUITAR, "P11-1 CRUNCH VIB/CE-1", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P11_2(1, InstrumentMode.ELECTRIC_GUITAR, "P11-2 MAXIMUM 451 BEND", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P11_3(8, InstrumentMode.ELECTRIC_GUITAR, "P11-3 MELLOW JAZZ CLN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P11_4(4, InstrumentMode.ELECTRIC_GUITAR, "P11-4 JC-120 OCT FUZZ", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P11_5(30, InstrumentMode.ELECTRIC_GUITAR, "P11-5 BRIT STACK 57", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P12_1(6, InstrumentMode.ELECTRIC_GUITAR, "P12-1 VINTAGE FLOYD", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P12_2(30, InstrumentMode.ELECTRIC_GUITAR, "P12-2 BRIT WALL", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P12_3(6, InstrumentMode.ELECTRIC_GUITAR, "P12-3 WILD STEREO", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P12_4(6, InstrumentMode.ELECTRIC_GUITAR, "P12-4 SPRINGY BLUES", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P12_5(6, InstrumentMode.ELECTRIC_GUITAR, "P12-5 VINTAGE VIBE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P13_1(1, InstrumentMode.ELECTRIC_GUITAR, "P13-1 GIG READY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P13_2(1, InstrumentMode.ELECTRIC_GUITAR, "P13-2 GREEN STEW", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P13_3(6, InstrumentMode.ELECTRIC_GUITAR, "P13-3 EDGY DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P13_4(1, InstrumentMode.ELECTRIC_GUITAR, "P13-4 EMPRESS MAY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P13_5(9, InstrumentMode.ELECTRIC_GUITAR, "P13-5 DELUXE CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P14_1(8, InstrumentMode.ELECTRIC_GUITAR, "P14-1 DEFRETTER", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P14_2(6, InstrumentMode.ELECTRIC_GUITAR, "P14-2 STEREO TREMOLO", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P14_3(5, InstrumentMode.ELECTRIC_GUITAR, "P14-3 FLYING WAH", "Multi-FX factory · wah filter voicing", -1, "GT-Style Multi-FX"),
    GT_P14_4(8, InstrumentMode.ELECTRIC_GUITAR, "P14-4 JAZZ OF TODAY", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P14_5(9, InstrumentMode.ELECTRIC_GUITAR, "P14-5 BLUES GUITAR TX", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P15_1(6, InstrumentMode.ELECTRIC_GUITAR, "P15-1 SHOEGAZER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P15_2(31, InstrumentMode.ELECTRIC_GUITAR, "P15-2 OVERTONE LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P15_3(8, InstrumentMode.ELECTRIC_GUITAR, "P15-3 PRE REVERB RETRO", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P15_4(6, InstrumentMode.ELECTRIC_GUITAR, "P15-4 LATE 60s > VIB", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P15_5(6, InstrumentMode.ELECTRIC_GUITAR, "P15-5 STEP PHASER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P16_1(6, InstrumentMode.ELECTRIC_GUITAR, "P16-1 ORGANISH DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P16_2(6, InstrumentMode.ELECTRIC_GUITAR, "P16-2 SG PAN CTL2:BPM", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P16_3(1, InstrumentMode.ELECTRIC_GUITAR, "P16-3 DOUBLE X-DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P16_4(6, InstrumentMode.ELECTRIC_GUITAR, "P16-4 FILTERED DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P16_5(1, InstrumentMode.ELECTRIC_GUITAR, "P16-5 MULTIPLE EFFECTS", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P17_1(1, InstrumentMode.ELECTRIC_GUITAR, "P17-1 CTL1:DIMINISH DL", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P17_2(6, InstrumentMode.ELECTRIC_GUITAR, "P17-2 P.SHIFT DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P17_3(6, InstrumentMode.ELECTRIC_GUITAR, "P17-3 SITAR+AG STEREO", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P17_4(8, InstrumentMode.ELECTRIC_GUITAR, "P17-4 TRADITIONAL RT", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P17_5(3, InstrumentMode.ELECTRIC_GUITAR, "P17-5 PROG METAL", "Multi-FX factory · metal voicing", -1, "GT-Style Multi-FX"),
    GT_P18_1(6, InstrumentMode.ELECTRIC_GUITAR, "P18-1 AMBIENT SWELL", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P18_2(1, InstrumentMode.ELECTRIC_GUITAR, "P18-2 TR SPEED CHANGES", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P18_3(31, InstrumentMode.ELECTRIC_GUITAR, "P18-3 BUTTERSMOOTH LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P18_4(1, InstrumentMode.ELECTRIC_GUITAR, "P18-4 CEE CEE TOP 4 LP", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P18_5(6, InstrumentMode.ELECTRIC_GUITAR, "P18-5 SCRIPT PHASED MS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P19_1(1, InstrumentMode.ELECTRIC_GUITAR, "P19-1 COLD SHOOTING>ST", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P19_2(8, InstrumentMode.ELECTRIC_GUITAR, "P19-2 AC GTR'S LOVE IT", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P19_3(1, InstrumentMode.ELECTRIC_GUITAR, "P19-3 BRIDGE OF S.", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P19_4(8, InstrumentMode.ELECTRIC_GUITAR, "P19-4 DREADNOUGHT SLIDE", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P19_5(31, InstrumentMode.ELECTRIC_GUITAR, "P19-5 VH ON STEROIDS", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P20_1(6, InstrumentMode.ELECTRIC_GUITAR, "P20-1 LEZLY VIBES", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P20_2(6, InstrumentMode.ELECTRIC_GUITAR, "P20-2 OMNISPHERICAL", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P20_3(6, InstrumentMode.ELECTRIC_GUITAR, "P20-3 RINGMOD BASS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P20_4(8, InstrumentMode.ELECTRIC_GUITAR, "P20-4 FRETLESS GUITAR", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P20_5(8, InstrumentMode.ELECTRIC_GUITAR, "P20-5 MEAN CLEAN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P21_1(6, InstrumentMode.ELECTRIC_GUITAR, "P21-1 SLICE AND DICE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P21_2(4, InstrumentMode.ELECTRIC_GUITAR, "P21-2 OCTFUZZ>NECK PU", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P21_3(7, InstrumentMode.ELECTRIC_GUITAR, "P21-3 HEAVY PARKING", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P21_4(6, InstrumentMode.ELECTRIC_GUITAR, "P21-4 CLEAN + PAD", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P21_5(31, InstrumentMode.ELECTRIC_GUITAR, "P21-5 X-HI GAIN LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P22_1(1, InstrumentMode.ELECTRIC_GUITAR, "P22-1 DRIVE + BASS", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P22_2(6, InstrumentMode.ELECTRIC_GUITAR, "P22-2 PRIME SHIMMER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P22_3(6, InstrumentMode.ELECTRIC_GUITAR, "P22-3 TERA SHIMMER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P22_4(6, InstrumentMode.ELECTRIC_GUITAR, "P22-4 FLANGER REVERB", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P22_5(6, InstrumentMode.ELECTRIC_GUITAR, "P22-5 PANNING DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P23_1(6, InstrumentMode.ELECTRIC_GUITAR, "P23-1 DRIVE + ORGAN", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P23_2(9, InstrumentMode.ELECTRIC_GUITAR, "P23-2 PRIME X-CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P23_3(7, InstrumentMode.ELECTRIC_GUITAR, "P23-3 HEAVY X-METAL", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P23_4(6, InstrumentMode.ELECTRIC_GUITAR, "P23-4 +1OCT CHORUS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P23_5(1, InstrumentMode.ELECTRIC_GUITAR, "P23-5 CLEAN + DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P24_1(1, InstrumentMode.ELECTRIC_GUITAR, "P24-1 SUPER OCTAVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P24_2(31, InstrumentMode.ELECTRIC_GUITAR, "P24-2 TIGHT ECHO LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P24_3(2, InstrumentMode.ELECTRIC_GUITAR, "P24-3 DIST + CLEAN REV", "Multi-FX factory · distortion voicing", -1, "GT-Style Multi-FX"),
    GT_P24_4(8, InstrumentMode.ELECTRIC_GUITAR, "P24-4 CRYSTAL CLEAN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P24_5(6, InstrumentMode.ELECTRIC_GUITAR, "P24-5 PANNING PHASE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P25_1(6, InstrumentMode.ELECTRIC_GUITAR, "P25-1 DEEP PAD ECHO", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P25_2(6, InstrumentMode.ELECTRIC_GUITAR, "P25-2 FAST MOD PHASE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P25_3(6, InstrumentMode.ELECTRIC_GUITAR, "P25-3 VIBRATREMOLO", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P25_4(31, InstrumentMode.ELECTRIC_GUITAR, "P25-4 LIGHT CHORUS LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P25_5(6, InstrumentMode.ELECTRIC_GUITAR, "P25-5 RINGMOD BELL", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P26_1(6, InstrumentMode.ELECTRIC_GUITAR, "P26-1 FOR NYLON STRING", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P26_2(9, InstrumentMode.ELECTRIC_GUITAR, "P26-2 GROOVY FUNK", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P26_3(8, InstrumentMode.ELECTRIC_GUITAR, "P26-3 THINLINE JAZZ", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P26_4(1, InstrumentMode.ELECTRIC_GUITAR, "P26-4 ACO/DRIVE MIX", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P26_5(31, InstrumentMode.ELECTRIC_GUITAR, "P26-5 LEAD DELAY", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P27_1(6, InstrumentMode.ELECTRIC_GUITAR, "P27-1 DELAYED CLEAN", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P27_2(6, InstrumentMode.ELECTRIC_GUITAR, "P27-2 DELAYED FLANGER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P27_3(1, InstrumentMode.ELECTRIC_GUITAR, "P27-3 HI-GAIN JC", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P27_4(6, InstrumentMode.ELECTRIC_GUITAR, "P27-4 4-STEP CRUNCH", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P27_5(8, InstrumentMode.ELECTRIC_GUITAR, "P27-5 FRETLESS BALLAD", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P28_1(4, InstrumentMode.ELECTRIC_GUITAR, "P28-1 FUZZY RING MOD", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P28_2(8, InstrumentMode.ELECTRIC_GUITAR, "P28-2 SITAR FANTASY", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P28_3(8, InstrumentMode.ELECTRIC_GUITAR, "P28-3 BASS HOLD:CTL1", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P28_4(6, InstrumentMode.ELECTRIC_GUITAR, "P28-4 PULSE WAVE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P28_5(4, InstrumentMode.ELECTRIC_GUITAR, "P28-5 STEP FUZZ", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P29_1(1, InstrumentMode.ELECTRIC_GUITAR, "P29-1 COMP DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P29_2(6, InstrumentMode.ELECTRIC_GUITAR, "P29-2 SLICE+EXP FILTER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P29_3(31, InstrumentMode.ELECTRIC_GUITAR, "P29-3 CLEAN<>LEAD VARI", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P29_4(6, InstrumentMode.ELECTRIC_GUITAR, "P29-4 EXP OUTER SPACE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P29_5(2, InstrumentMode.ELECTRIC_GUITAR, "P29-5 DEAD OR ALIVE", "Multi-FX factory · distortion voicing", -1, "GT-Style Multi-FX"),
    GT_P30_1(6, InstrumentMode.ELECTRIC_GUITAR, "P30-1 JAZZ FUNK CHORUS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P30_2(8, InstrumentMode.ELECTRIC_GUITAR, "P30-2 NEW CHAPTER JAZZ", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P30_3(31, InstrumentMode.ELECTRIC_GUITAR, "P30-3 VELVET LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P30_4(31, InstrumentMode.ELECTRIC_GUITAR, "P30-4 PEDAL SEARING LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P30_5(30, InstrumentMode.ELECTRIC_GUITAR, "P30-5 BITING STACK LD", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P31_1(1, InstrumentMode.ELECTRIC_GUITAR, "P31-1 DUAL TONALITY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P31_2(1, InstrumentMode.ELECTRIC_GUITAR, "P31-2 OVERTONAL DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P31_3(1, InstrumentMode.ELECTRIC_GUITAR, "P31-3 WEST COAST OD", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P31_4(7, InstrumentMode.ELECTRIC_GUITAR, "P31-4 ST CORE METAL", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P31_5(2, InstrumentMode.ELECTRIC_GUITAR, "P31-5 JC+DIST+DLY=YEAH", "Multi-FX factory · distortion voicing", -1, "GT-Style Multi-FX"),
    GT_P32_1(30, InstrumentMode.ELECTRIC_GUITAR, "P32-1 MIXTURE ROCK MOD", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P32_2(6, InstrumentMode.ELECTRIC_GUITAR, "P32-2 STEREO X", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P32_3(1, InstrumentMode.ELECTRIC_GUITAR, "P32-3 INFINITE THING", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P32_4(30, InstrumentMode.ELECTRIC_GUITAR, "P32-4 BRITIFIER", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P32_5(6, InstrumentMode.ELECTRIC_GUITAR, "P32-5 CRESCENT DELAY", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P33_1(1, InstrumentMode.ELECTRIC_GUITAR, "P33-1 FLEXIBLE RIG", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P33_2(7, InstrumentMode.ELECTRIC_GUITAR, "P33-2 DJENTY CORE", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P33_3(3, InstrumentMode.ELECTRIC_GUITAR, "P33-3 CLASSIC METAL", "Multi-FX factory · metal voicing", -1, "GT-Style Multi-FX"),
    GT_P33_4(31, InstrumentMode.ELECTRIC_GUITAR, "P33-4 TWIN CRIMSON LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P33_5(9, InstrumentMode.ELECTRIC_GUITAR, "P33-5 PLEXI CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P34_1(31, InstrumentMode.ELECTRIC_GUITAR, "P34-1 PLEXI SOLO", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P34_2(6, InstrumentMode.ELECTRIC_GUITAR, "P34-2 ROTARY PHAZE", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P34_3(6, InstrumentMode.ELECTRIC_GUITAR, "P34-3 SUPER SLICER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P34_4(6, InstrumentMode.ELECTRIC_GUITAR, "P34-4 FAT FLANGER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P34_5(8, InstrumentMode.ELECTRIC_GUITAR, "P34-5 AC RESO STANDARD", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P35_1(6, InstrumentMode.ELECTRIC_GUITAR, "P35-1 RETRO RING SEQ", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P35_2(6, InstrumentMode.ELECTRIC_GUITAR, "P35-2 7TH WONDER", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P35_3(6, InstrumentMode.ELECTRIC_GUITAR, "P35-3 MOVING CHORDS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P35_4(8, InstrumentMode.ELECTRIC_GUITAR, "P35-4 JC-120 FLAT", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P35_5(1, InstrumentMode.ELECTRIC_GUITAR, "P35-5 BOUTIQUE 87 PH", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P36_1(1, InstrumentMode.ELECTRIC_GUITAR, "P36-1 X-MOD 451 OT", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P36_2(8, InstrumentMode.ELECTRIC_GUITAR, "P36-2 TWIN ST FLAT PH", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P36_3(1, InstrumentMode.ELECTRIC_GUITAR, "P36-3 DIAMOND 421 DLY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P36_4(6, InstrumentMode.ELECTRIC_GUITAR, "P36-4 SYNTH S-BEND RES", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P36_5(1, InstrumentMode.ELECTRIC_GUITAR, "P36-5 JUGGERNAUT FLAT", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P37_1(6, InstrumentMode.ELECTRIC_GUITAR, "P37-1 NATURAL 451 TERA", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P37_2(9, InstrumentMode.ELECTRIC_GUITAR, "P37-2 X-CRUNCH 57 TR", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P37_3(1, InstrumentMode.ELECTRIC_GUITAR, "P37-3 SUPREME 421 OVER", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P37_4(31, InstrumentMode.ELECTRIC_GUITAR, "P37-4 S-BEND DRIVE LD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P37_5(8, InstrumentMode.ELECTRIC_GUITAR, "P37-5 DELUXE 57 FZ", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P38_1(8, InstrumentMode.ELECTRIC_GUITAR, "P38-1 SOULFUL CLEAN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P38_2(30, InstrumentMode.ELECTRIC_GUITAR, "P38-2 AUSSIE ROCK", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P38_3(9, InstrumentMode.ELECTRIC_GUITAR, "P38-3 SWAMPY BAYOU", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P38_4(9, InstrumentMode.ELECTRIC_GUITAR, "P38-4 STAR SPANGLED", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P38_5(9, InstrumentMode.ELECTRIC_GUITAR, "P38-5 ARLINGTON COWBOY", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P39_1(7, InstrumentMode.ELECTRIC_GUITAR, "P39-1 DJENTLEMAN", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P39_2(9, InstrumentMode.ELECTRIC_GUITAR, "P39-2 LOFI BLUES", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P39_3(8, InstrumentMode.ELECTRIC_GUITAR, "P39-3 CREAMY", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P39_4(1, InstrumentMode.ELECTRIC_GUITAR, "P39-4 SE MIX", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P39_5(31, InstrumentMode.ELECTRIC_GUITAR, "P39-5 FAT COMP LEAD", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P40_1(6, InstrumentMode.ELECTRIC_GUITAR, "P40-1 SPACED OUT", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P40_2(6, InstrumentMode.ELECTRIC_GUITAR, "P40-2 ELECTRIC SPANISH", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P40_3(6, InstrumentMode.ELECTRIC_GUITAR, "P40-3 MAGIC CARPET", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P40_4(1, InstrumentMode.ELECTRIC_GUITAR, "P40-4 NOTHING 4 MONEY", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P40_5(6, InstrumentMode.ELECTRIC_GUITAR, "P40-5 ORGANIC FOOD", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P41_1(6, InstrumentMode.ELECTRIC_GUITAR, "P41-1 5TH DIMENSION", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P41_2(1, InstrumentMode.ELECTRIC_GUITAR, "P41-2 CLASS-A HEAVEN", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P41_3(9, InstrumentMode.ELECTRIC_GUITAR, "P41-3 DREADLOCK CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P41_4(6, InstrumentMode.ELECTRIC_GUITAR, "P41-4 SURROUND GUITAR", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P41_5(6, InstrumentMode.ELECTRIC_GUITAR, "P41-5 IBIZA TRANCE GTR", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P42_1(1, InstrumentMode.ELECTRIC_GUITAR, "P42-1 SOULFUL GAIN", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P42_2(6, InstrumentMode.ELECTRIC_GUITAR, "P42-2 SOARING CLEANS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P42_3(1, InstrumentMode.ELECTRIC_GUITAR, "P42-3 DANCING GUITAR", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P42_4(1, InstrumentMode.ELECTRIC_GUITAR, "P42-4 70s BARRACUDA OD", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P42_5(6, InstrumentMode.ELECTRIC_GUITAR, "P42-5 STEREO SMACK", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P43_1(30, InstrumentMode.ELECTRIC_GUITAR, "P43-1 WICKED STACK", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P43_2(30, InstrumentMode.ELECTRIC_GUITAR, "P43-2 LIVE IN POMPEII", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P43_3(8, InstrumentMode.ELECTRIC_GUITAR, "P43-3 SLIDE BAR", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P43_4(8, InstrumentMode.ELECTRIC_GUITAR, "P43-4 CLEAR STREAM", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P43_5(9, InstrumentMode.ELECTRIC_GUITAR, "P43-5 PLAIN TOP BLUES", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P44_1(30, InstrumentMode.ELECTRIC_GUITAR, "P44-1 30 ROCKS", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P44_2(9, InstrumentMode.ELECTRIC_GUITAR, "P44-2 ORANGE JUICE", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P44_3(1, InstrumentMode.ELECTRIC_GUITAR, "P44-3 BIN HERE BEFORE?", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P44_4(7, InstrumentMode.ELECTRIC_GUITAR, "P44-4 DEATH BY HM-2", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P44_5(30, InstrumentMode.ELECTRIC_GUITAR, "P44-5 PLEX PICKIN'", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P45_1(1, InstrumentMode.ELECTRIC_GUITAR, "P45-1 QUAD RIDER", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P45_2(6, InstrumentMode.ELECTRIC_GUITAR, "P45-2 ECHO CRUNCH", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P45_3(9, InstrumentMode.ELECTRIC_GUITAR, "P45-3 100 perCenta", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P45_4(6, InstrumentMode.ELECTRIC_GUITAR, "P45-4 AMBIENT TRIADS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P45_5(7, InstrumentMode.ELECTRIC_GUITAR, "P45-5 UBER METAL", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P46_1(30, InstrumentMode.ELECTRIC_GUITAR, "P46-1 CLASSIC ROCKER", "Multi-FX factory · brown stack voicing", -1, "GT-Style Multi-FX"),
    GT_P46_2(9, InstrumentMode.ELECTRIC_GUITAR, "P46-2 POP ROCK RHYTHM", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P46_3(7, InstrumentMode.ELECTRIC_GUITAR, "P46-3 BRUTAL UBERCORE", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P46_4(7, InstrumentMode.ELECTRIC_GUITAR, "P46-4 BIG BOTTOM", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P46_5(7, InstrumentMode.ELECTRIC_GUITAR, "P46-5 MOLTEN CORE", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P47_1(8, InstrumentMode.ELECTRIC_GUITAR, "P47-1 STUDIO BASS", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P47_2(9, InstrumentMode.ELECTRIC_GUITAR, "P47-2 ROCK BASS CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P47_3(1, InstrumentMode.ELECTRIC_GUITAR, "P47-3 X-DRIVE BASS", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P47_4(8, InstrumentMode.ELECTRIC_GUITAR, "P47-4 CLEAN ROCK BASS", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P47_5(5, InstrumentMode.ELECTRIC_GUITAR, "P47-5 T WAH BASS", "Multi-FX factory · wah filter voicing", -1, "GT-Style Multi-FX"),
    GT_P48_1(6, InstrumentMode.ELECTRIC_GUITAR, "P48-1 SLAP BASS CHORUS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P48_2(8, InstrumentMode.ELECTRIC_GUITAR, "P48-2 KINGS BASS", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P48_3(4, InstrumentMode.ELECTRIC_GUITAR, "P48-3 DEEP FUZZ BASS", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P48_4(2, InstrumentMode.ELECTRIC_GUITAR, "P48-4 DIST ROCK BASS", "Multi-FX factory · distortion voicing", -1, "GT-Style Multi-FX"),
    GT_P48_5(6, InstrumentMode.ELECTRIC_GUITAR, "P48-5 MONO BASS CLOUD", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P49_1(6, InstrumentMode.ELECTRIC_GUITAR, "P49-1 FLANGE BASS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P49_2(7, InstrumentMode.ELECTRIC_GUITAR, "P49-2 RAGE BASS", "Multi-FX factory · high-gain voicing", -1, "GT-Style Multi-FX"),
    GT_P49_3(6, InstrumentMode.ELECTRIC_GUITAR, "P49-3 SYNTHY OCT BASS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P49_4(4, InstrumentMode.ELECTRIC_GUITAR, "P49-4 FUZZ BASS", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GT_P49_5(6, InstrumentMode.ELECTRIC_GUITAR, "P49-5 TERA BASS", "Multi-FX factory · modulated clean voicing", -1, "GT-Style Multi-FX"),
    GT_P50_1(8, InstrumentMode.ELECTRIC_GUITAR, "P50-1 LOOPER CLEAN", "Multi-FX factory · studio clean voicing", -1, "GT-Style Multi-FX"),
    GT_P50_2(9, InstrumentMode.ELECTRIC_GUITAR, "P50-2 LOOPER CRUNCH", "Multi-FX factory · crunch voicing", -1, "GT-Style Multi-FX"),
    GT_P50_3(1, InstrumentMode.ELECTRIC_GUITAR, "P50-3 LOOPER DRIVE", "Multi-FX factory · overdrive voicing", -1, "GT-Style Multi-FX"),
    GT_P50_4(31, InstrumentMode.ELECTRIC_GUITAR, "P50-4 LOOPER SOLO", "Multi-FX factory · lead sustain voicing", -1, "GT-Style Multi-FX"),
    GT_P50_5(4, InstrumentMode.ELECTRIC_GUITAR, "P50-5 LOOPER -1OCT", "Multi-FX factory · fuzz voicing", -1, "GT-Style Multi-FX"),
    GUITAR_CRYBABY(5, InstrumentMode.ELECTRIC_GUITAR, "Crying Wah", "Envelope auto-wah sweep", -1, "Wah"),
    GUITAR_VOX_WAH(5, InstrumentMode.ELECTRIC_GUITAR, "Sixties Wah", "Vintage vocal wah", -1, "Wah"),
    GUITAR_BAD_HORSIE(5, InstrumentMode.ELECTRIC_GUITAR, "Liquid Wah", "Smooth contour wah", -1, "Wah"),
    GUITAR_CE2(6, InstrumentMode.ELECTRIC_GUITAR, "Classic Chorus", "Lush analog chorus", -1, "Chorus"),
    GUITAR_MXR_CHORUS(6, InstrumentMode.ELECTRIC_GUITAR, "Warm Chorus", "Warm watery modulation", -1, "Chorus"),
    GUITAR_CORONA(6, InstrumentMode.ELECTRIC_GUITAR, "Shimmer Chorus", "Studio shimmer chorus", -1, "Chorus"),

    BASS_SANSAMP(11, InstrumentMode.BASS, "Drive DI", "Preamp drive DI", -1, "Preamp"),
    BASS_MXR_M81(10, InstrumentMode.BASS, "Clean Preamp", "Clean studio DI", -1, "Preamp"),
    BASS_TONE_HAMMER(11, InstrumentMode.BASS, "Warm Preamp", "Warm preamp", -1, "Preamp"),
    BASS_AMPEG_SGT(11, InstrumentMode.BASS, "Tube Stack Preamp", "Classic tube-stack preamp", -1, "Preamp"),
    BASS_ORIGIN_VINTAGE(10, InstrumentMode.BASS, "Vintage Tube DI", "Vintage tube DI", -1, "Preamp"),
    BASS_DARKGLASS_B7K(13, InstrumentMode.BASS, "Modern Distortion", "Modern grit", -1, "Drive"),
    BASS_ALPHA_OMEGA(13, InstrumentMode.BASS, "Heavy Distortion", "Heavy drive", -1, "Drive"),
    BASS_BOSS_ODB3(11, InstrumentMode.BASS, "Overdrive", "Overdrive blend", -1, "Drive"),
    BASS_BASS_BIG_MUFF(13, InstrumentMode.BASS, "Fuzz", "Bass fuzz", -1, "Fuzz"),
    BASS_ENVELOPE(12, InstrumentMode.BASS, "Envelope Filter", "Funk auto-filter", -1, "Filter & Synth"),
    BASS_OCTAVE_DRIVE(12, InstrumentMode.BASS, "Octaver + Drive", "Synth bass", -1, "Filter & Synth"),

    SIG_NORD_GRAND(20, InstrumentMode.PIANO, "Pop Grand", "Modern bright, compressed pop grand", 0, "Signature Tones"),
    SIG_CP80(21, InstrumentMode.PIANO, "80s Electric Grand", "80s electric grand (Genesis / Tears for Fears)", 2, "Signature Tones"),
    SIG_SUITCASE(21, InstrumentMode.PIANO, "Suitcase Rhodes", "Chorused Rhodes ('Just the Two of Us')", 4, "Signature Tones"),
    SIG_WURLI(21, InstrumentMode.PIANO, "Vintage Wurly", "Tremolo reed piano (soul / classic rock)", 4, "Signature Tones"),
    SIG_DX7(20, InstrumentMode.PIANO, "FM Full Tines", "80s ballad FM electric piano", 5, "Signature Tones"),
    SIG_B3(22, InstrumentMode.PIANO, "Rotary Organ", "Overdriven rotary organ", 18, "Signature Tones"),
    SIG_CLAV(21, InstrumentMode.PIANO, "Funky Clav", "Wah clav ('Superstition')", 7, "Signature Tones"),
    SIG_M1(20, InstrumentMode.PIANO, "House Classic", "90s house & dance piano", 1, "Signature Tones"),

    // "Stage Rig" — a workstation channel setup (built-in GM voices, no download),
    // modeled on a Nord/Yamaha live-layering rig: three grands, two string
    // attacks, a bell, and a pad. Great as Layer / Mixer sources.
    RIG_ITALIAN_GRAND(20, InstrumentMode.PIANO, "Italian Grand", "Bright, articulate concert grand", 1, "Stage Rig"),
    RIG_BLACK_UPRIGHT(20, InstrumentMode.PIANO, "Black Upright", "Dark, intimate felt upright", 0, "Stage Rig"),
    RIG_VIRTUAL_G(20, InstrumentMode.PIANO, "Virtual G", "Clean full concert grand", 0, "Stage Rig"),
    RIG_LASTRING_SLOW(22, InstrumentMode.PIANO, "LAString Slow", "Swelling slow-attack string pad", 49, "Stage Rig"),
    RIG_LASTRING_FAST(22, InstrumentMode.PIANO, "LAString Fast", "Fast-attack string ensemble for rhythmic parts", 48, "Stage Rig"),
    RIG_D_BELLS(23, InstrumentMode.PIANO, "D Bells", "Glassy digital tubular bells", 14, "Stage Rig"),
    RIG_C_PAD(20, InstrumentMode.PIANO, "C - Pad", "Soft sustained synth pad", 89, "Stage Rig"),

    VIRTUAL_GUITAR_STARTER(21, InstrumentMode.PIANO, "FreePats Fender Starter",
            "CC0 sampled electric guitar · bridge pickup",
            0, "Guitar Instruments", "virtual_guitar_starter.sf2"),

    PIANO_LIB_00(22, InstrumentMode.PIANO, "Digital Marimba", "Sampled library sound", 0, "Organs & Other (Library)", "piano_lib_00.sf2"),
    PIANO_LIB_01(21, InstrumentMode.PIANO, "FM Wurly", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_01.sf2"),
    PIANO_LIB_02(20, InstrumentMode.PIANO, "Synth Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_02.sf2"),
    PIANO_LIB_04(20, InstrumentMode.PIANO, "TekPiano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_04.sf2"),
    PIANO_LIB_05(21, InstrumentMode.PIANO, "Soft Wurly", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_05.sf2"),
    PIANO_LIB_06(20, InstrumentMode.PIANO, "Vintage Digital Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_06.sf2"),
    PIANO_LIB_07(21, InstrumentMode.PIANO, "Soft Digital EP", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_07.sf2"),
    PIANO_LIB_08(21, InstrumentMode.PIANO, "Bright Electric Grand", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_08.sf2"),
    PIANO_LIB_09(20, InstrumentMode.PIANO, "Fantasy Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_09.sf2"),
    PIANO_LIB_11(20, InstrumentMode.PIANO, "Pop Rock Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_11.sf2"),
    PIANO_LIB_14(21, InstrumentMode.PIANO, "Rhodes 3", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_14.sf2"),
    PIANO_LIB_15(20, InstrumentMode.PIANO, "9MB Grand", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_15.sf2"),
    PIANO_LIB_19(21, InstrumentMode.PIANO, "Airy Rhodes", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_19.sf2"),
    PIANO_LIB_24(20, InstrumentMode.PIANO, "LK Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_24.sf2"),
    PIANO_LIB_26(20, InstrumentMode.PIANO, "Modern Concert Grand", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_26.sf2"),
    PIANO_LIB_27(21, InstrumentMode.PIANO, "Classic Rock Rhodes", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_27.sf2"),
    PIANO_LIB_28(20, InstrumentMode.PIANO, "Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_28.sf2"),
    PIANO_LIB_32(20, InstrumentMode.PIANO, "90s Module Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_32.sf2"),
    PIANO_LIB_34(20, InstrumentMode.PIANO, "Small Pianos Bank", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_34.sf2"),
    PIANO_LIB_35(20, InstrumentMode.PIANO, "New York Grand", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_35.sf2"),
    PIANO_LIB_36(20, InstrumentMode.PIANO, "Stage Digital Piano", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_36.sf2"),
    PIANO_LIB_38(21, InstrumentMode.PIANO, "FM Piano", "Sampled library sound", 0, "Electric Pianos (Library)", "piano_lib_38.sf2"),
    PIANO_LIB_41(20, InstrumentMode.PIANO, "Studio Upright", "Sampled library sound", 0, "Acoustic Pianos (Library)", "piano_lib_41.sf2"),
    // Sampled library — Acoustic grands
    STEINWAY_LIB(20, InstrumentMode.PIANO, "Concert Steinway", "Sampled Steinway Model-C · full 9-foot grand", 0, "Acoustic Pianos (Library)", "steinway_grand.sf2"),
    GIGA_LIB(20, InstrumentMode.PIANO, "Giga Grand", "Bright sampled pop/rock grand · Gigapiano", 0, "Acoustic Pianos (Library)", "giga_grand.sf2"),
    AI_GRAND_LIB(20, InstrumentMode.PIANO, "AI Concert Grand", "Sampled acoustic grand · natural decay", 0, "Acoustic Pianos (Library)", "ai_grand.sf2"),
    NICE_PIANO_LIB(20, InstrumentMode.PIANO, "Nice Piano", "Roland JV-1080 ROM grand · bright & clean", 0, "Acoustic Pianos (Library)", "nice_piano.sf2"),
    MOTIF_GRAND_LIB(20, InstrumentMode.PIANO, "Motif Concert", "Yamaha Motif ES sampled concert grand", 0, "Acoustic Pianos (Library)", "motif_grand.sf2"),
    COLA_GRAND_LIB(20, InstrumentMode.PIANO, "Cola Grand", "Warm looped sampled grand · Piano de Cola", 0, "Acoustic Pianos (Library)", "cola_grand.sf2"),
    // Sampled library — Electric pianos
    RHODES_MK1_LIB(21, InstrumentMode.PIANO, "Rhodes Mark I", "Sampled Rhodes Mark I · full-range tine EP", 0, "Electric Pianos (Library)", "rhodes_vs.sf2"),
    WURLI_DRY_LIB(21, InstrumentMode.PIANO, "Wurlitzer Dry", "Dry sampled Wurlitzer reed EP · no baked FX", 0, "Electric Pianos (Library)", "wurli_dry.sf2"),
    WURLY_DARK_LIB(21, InstrumentMode.PIANO, "Wurly Dark", "Dark Wurlitzer reed EP · mellow", 0, "Electric Pianos (Library)", "wurly_dark.sf2"),
    DX7_LIB(21, InstrumentMode.PIANO, "DX7 FM Piano", "Sampled Yamaha DX7 · classic FM electric", 0, "Electric Pianos (Library)", "dx7_ep.sf2"),
    // Same DX7 samples, voiced bright with a glockenspiel layer on the GM
    // channel for the bell partial the EP patch lacks — the 80s synth-pop
    // arpeggio tone. No extra asset.
    FM_BELL_LIB(21, InstrumentMode.PIANO, "FM Bell", "Glassy FM bell · 80s synth-pop arpeggio", 0, "Electric Pianos (Library)", "dx7_ep.sf2", 9),
    // Sampled library — Mallets
    MARIMBA_LIB(20, InstrumentMode.PIANO, "Marimba", "Korg IS-50 sampled marimba · mallet", 0, "Mallets (Library)", "marimba.sf2"),

    PIANO_CONCERT_GRAND(20, InstrumentMode.PIANO, "Concert Grand", "Clean 9-foot acoustic", 0, "Acoustic Pianos"),
    PIANO_STUDIO_GRAND(20, InstrumentMode.PIANO, "Studio Grand", "Bright, compressed pop piano", 1, "Acoustic Pianos"),
    PIANO_MELLOW_GRAND(20, InstrumentMode.PIANO, "Mellow Grand", "Warm jazz/classical ballad", 0, "Acoustic Pianos"),
    PIANO_ROCK_GRAND(20, InstrumentMode.PIANO, "Rock Piano", "Sharp mono grand that cuts", 1, "Acoustic Pianos"),
    PIANO_HONKY_TONK(20, InstrumentMode.PIANO, "Honky Tonk", "Detuned ragtime piano", 3, "Acoustic Pianos"),
    PIANO_HARPSICHORD(23, InstrumentMode.PIANO, "Harpsichord", "Plucked baroque keys", 6, "Acoustic Pianos"),

    PIANO_STAGE_TINE(21, InstrumentMode.PIANO, "Stage Tine", "Standard tine Rhodes", 4, "70s Electric Pianos"),
    PIANO_SUITCASE_73(21, InstrumentMode.PIANO, "Suitcase 73", "Warm vibrating Rhodes", 4, "70s Electric Pianos"),
    PIANO_AMPED_REED(21, InstrumentMode.PIANO, "Amped Reed", "Classic Wurly rock", 4, "70s Electric Pianos"),
    PIANO_TREMOLO_WURLY(21, InstrumentMode.PIANO, "Tremolo Wurly", "Pulsing Wurly", 4, "70s Electric Pianos"),
    PIANO_CLAV_FUNK(21, InstrumentMode.PIANO, "Clav Funk", "Percussive plucked clav", 7, "70s Electric Pianos"),
    PIANO_WAH_CLAV(21, InstrumentMode.PIANO, "Wah-Clav", "Clavinet through a wah", 7, "70s Electric Pianos"),
    PIANO_CP_GRAND(21, InstrumentMode.PIANO, "Stage Electric Grand", "70s stadium electric grand", 2, "70s Electric Pianos"),

    PIANO_FM_RHODES(20, InstrumentMode.PIANO, "FM Rhodes", "Crisp bell-like 80s EP", 5, "80s Electric Pianos"),
    PIANO_DX7(20, InstrumentMode.PIANO, "FM Electric Piano", "The classic FM preset", 5, "80s Electric Pianos"),
    PIANO_GLASSY_EP(23, InstrumentMode.PIANO, "Glassy E.P.", "Ice-cold digital chimes", 5, "80s Electric Pianos"),
    PIANO_DYNO(21, InstrumentMode.PIANO, "Dyno Tine EP", "Extra-bright modified Rhodes", 5, "80s Electric Pianos"),
    PIANO_LA_BALLAD(21, InstrumentMode.PIANO, "LA Ballad Piano", "Grand blended with synth", 5, "80s Electric Pianos"),

    PIANO_MUSIC_BOX(23, InstrumentMode.PIANO, "Music Box", "Wind-up toy chimes", 10, "Mallets & Bells"),
    PIANO_CELESTA(23, InstrumentMode.PIANO, "Celesta", "Bell-piano", 8, "Mallets & Bells"),
    PIANO_VIBRAPHONE(23, InstrumentMode.PIANO, "Vibraphone", "Jazz metal bars", 11, "Mallets & Bells"),
    PIANO_MARIMBA(23, InstrumentMode.PIANO, "Marimba", "Warm woody mallets", 12, "Mallets & Bells"),
    PIANO_GLOCKENSPIEL(23, InstrumentMode.PIANO, "Glockenspiel", "Crystalline metal bells", 9, "Mallets & Bells"),
    PIANO_TUBULAR_BELLS(23, InstrumentMode.PIANO, "Tubular Bells", "Church-tower bells", 14, "Mallets & Bells"),

    PIANO_JAZZ_B3(22, InstrumentMode.PIANO, "Jazz Organ", "Warm slow-rotary organ", 16, "Organs"),
    PIANO_ROCK_ORGAN(22, InstrumentMode.PIANO, "Rock Organ", "Screaming overdriven drawbars", 18, "Organs"),
    PIANO_GOSPEL_B3(22, InstrumentMode.PIANO, "Gospel Organ", "Deep heavy-vibrato organ", 16, "Organs"),
    PIANO_VOX(22, InstrumentMode.PIANO, "Transistor Combo", "Thin 60s combo organ", 17, "Organs"),
    PIANO_CHURCH(22, InstrumentMode.PIANO, "Church Organ", "Majestic pipe organ", 19, "Organs"),

    PIANO_80S_BRASS(20, InstrumentMode.PIANO, "80s Brass", "Warm poly-synth brass", 62, "Synth Leads & Brass"),
    PIANO_SOFT_BRASS(20, InstrumentMode.PIANO, "Soft Brass", "Mellow, gentle synth brass pad — not aggressive", 62, "Synth Leads & Brass"),
    PIANO_JUMP_BRASS(20, InstrumentMode.PIANO, "Jump Brass", "Aggressive stab brass", 63, "Synth Leads & Brass"),
    PIANO_RESO_LEAD(20, InstrumentMode.PIANO, "Reso Lead", "Screaming resonant lead", 81, "Synth Leads & Brass"),
    PIANO_SQUARE_LEAD(20, InstrumentMode.PIANO, "Square Lead", "Hollow game-style lead", 80, "Synth Leads & Brass"),
    PIANO_SAW_LEAD(20, InstrumentMode.PIANO, "Saw Lead", "Buzzing aggressive lead", 81, "Synth Leads & Brass"),
    PIANO_ELECTRIC_DREAMS(20, InstrumentMode.PIANO, "Electric Dreams Lead", "Bright saw arp lead — Moroder 'Together in Electric Dreams'", 81, "Synth Leads & Brass"),
    PIANO_FIREFLY(23, InstrumentMode.PIANO, "Firefly Melody", "Custom pluck lead — 'Fireflies' intro (melody layer)", 0, "Synth Leads & Brass", "firefly_lead.sf2"),
    PIANO_FIREFLY_CHORDS(23, InstrumentMode.PIANO, "Firefly Chords", "Soft warm stab — 'Fireflies' chord layer", 0, "Synth Leads & Brass", "firefly_chords.sf2"),

    PIANO_SYNTH_BASS(20, InstrumentMode.PIANO, "Synth Bass", "Warm round analog synth bass — 80s New Order pulse", 38, "Synth Bass"),
    PIANO_SYNTH_BASS_2(20, InstrumentMode.PIANO, "Synth Bass 2", "Brighter, resonant synth bass", 39, "Synth Bass"),

    PIANO_AHH_CHOIR(22, InstrumentMode.PIANO, "Ahh Choir", "Full vocal 'ahh' ensemble pad", 52, "Voices & Strings"),
    PIANO_OHH_VOICES(22, InstrumentMode.PIANO, "Ohh Voices", "Soft 'ohh' vocal ensemble", 53, "Voices & Strings"),
    PIANO_SYNTH_VOICE(22, InstrumentMode.PIANO, "Synth Voice", "Airy synthetic vocal lead", 54, "Voices & Strings"),
    PIANO_SPACE_VOICE(22, InstrumentMode.PIANO, "Space Voice", "Ethereal breathy choir pad", 91, "Voices & Strings"),
    PIANO_STRINGS(22, InstrumentMode.PIANO, "String Section", "Orchestral strings", 48, "Voices & Strings"),
    PIANO_SLOW_STRINGS(22, InstrumentMode.PIANO, "Slow Strings", "Soft swelling string pad", 49, "Voices & Strings"),

    PIANO_HOUSE(20, InstrumentMode.PIANO, "House Piano", "Punchy compressed club piano", 1, "90s Dance"),
    PIANO_CLUB_ORGAN(22, InstrumentMode.PIANO, "Club Organ", "Hollow percussive organ", 18, "90s Dance"),
    PIANO_PULSE_BASS(20, InstrumentMode.PIANO, "Pulse Bass", "Deep synth dance bass", 38, "90s Dance"),
    PIANO_MELLOTRON(21, InstrumentMode.PIANO, "Tape Strings", "Grainy tape-loop strings", 51, "90s Dance"),

    PIANO_STACCATO_HEAVEN(22, InstrumentMode.PIANO, "Staccato Heaven", "80s pizzicato stab over swelling strings", 45, "Pads & Strings", 49),
    PIANO_CELLO_ORGAN(22, InstrumentMode.PIANO, "Cello Organ", "Organ-fast attack with a dark cello body — made for staccato", 18, "Pads & Strings", 42),
    PIANO_WARM_PAD(20, InstrumentMode.PIANO, "Warm Pad", "Soft slow-fading pad", 89, "Pads & Strings"),
    PIANO_ANALOG_STRINGS(21, InstrumentMode.PIANO, "Analog Strings", "Thick vintage synth strings", 51, "Pads & Strings"),
    PIANO_80S_STRINGS(21, InstrumentMode.PIANO, "80s Strings", "Chorused string-machine pad — New Order 'State of the Nation' drama", 50, "Pads & Strings"),
    PIANO_ORCH_STRINGS(21, InstrumentMode.PIANO, "Orchestral Strings", "Sampled violins and cellos", 48, "Pads & Strings"),
    PIANO_PIZZICATO(21, InstrumentMode.PIANO, "Pizzicato", "Short plucked strings", 45, "Pads & Strings"),
    PIANO_CINEMATIC_PAD(20, InstrumentMode.PIANO, "Cinematic Pad", "Dark evolving sci-fi texture", 94, "Pads & Strings"),
    PIANO_SWEEP_PAD(20, InstrumentMode.PIANO, "Sweep Pad", "Washing wave pad", 95, "Pads & Strings"),

    // Vintage-workstation sound-alikes, built from the GM font (some layered).
    M1_PIANO(20, InstrumentMode.PIANO, "Workstation Piano", "Bright compressed house piano", 1, "Vintage Workstation"),
    M1_ORGAN(22, InstrumentMode.PIANO, "House Organ", "Percussive house organ ('Show Me Love')", 17, "Vintage Workstation"),
    M1_UNIVERSE(22, InstrumentMode.PIANO, "Universe", "Breathy voice pad with bell sparkle", 91, "Vintage Workstation", 9),
    M1_CHOIR(22, InstrumentMode.PIANO, "Synth Choir", "Warm 'ahh' vocal ensemble", 52, "Vintage Workstation"),
    M1_LORE(21, InstrumentMode.PIANO, "Lore", "Ethnic flute floating over a soft pad", 75, "Vintage Workstation", 89),
    M1_MAGICAL(23, InstrumentMode.PIANO, "Magical", "Glassy crystal bells with celesta chime", 98, "Vintage Workstation", 8),
    M1_POLE(21, InstrumentMode.PIANO, "Pole", "Hollow bowed synth pad", 92, "Vintage Workstation"),
    M1_POWER_HIT(21, InstrumentMode.PIANO, "Power Hit", "Big 80s orchestra stab", 55, "Vintage Workstation"),
    M1_STRINGS(21, InstrumentMode.PIANO, "Silk Strings", "Silky analog-style string ensemble", 50, "Vintage Workstation"),
    M1_BRASS(21, InstrumentMode.PIANO, "Layered Brass", "Fat layered synth brass stab", 61, "Vintage Workstation", 62),
    M1_FRETLESS(20, InstrumentMode.PIANO, "Fretless", "Singing fretless bass", 35, "Vintage Workstation"),
    M1_PICK_BASS(20, InstrumentMode.PIANO, "Pick Bass", "Tight picked electric bass", 34, "Vintage Workstation"),
    M1_VIBES(23, InstrumentMode.PIANO, "Vibes", "Mellow jazz vibraphone", 11, "Vintage Workstation"),
    M1_WHISTLE(21, InstrumentMode.PIANO, "Whistle", "Solo whistle lead", 78, "Vintage Workstation"),

    // ---- Stylophone: pocket stylus-synth buzzes, drones and leads.
    // Best played with the Slide chip on — the stylus glide is the sound. ----
    STYLO_CLASSIC(20, InstrumentMode.PIANO, "Classic Stylo", "The original buzzy pocket-synth lead", 81, "Stylophone"),
    STYLO_SQUARE(20, InstrumentMode.PIANO, "Square Buzz", "Hollow square-wave stylus tone", 80, "Stylophone"),
    STYLO_REED(22, InstrumentMode.PIANO, "Reed Buzz", "Reedy vintage buzz — closest to the 60s original", 20, "Stylophone"),
    STYLO_TREBLE(20, InstrumentMode.PIANO, "Treble Buzz", "Thin biting stylus buzz that cuts any mix", 84, "Stylophone"),
    STYLO_SPACE(20, InstrumentMode.PIANO, "Space Lead", "Late-60s space-rock stylus lead over a choir haze", 81, "Stylophone", 91),
    STYLO_DOUBLE(20, InstrumentMode.PIANO, "Double Buzz", "Saw and square stacked — extra thick", 81, "Stylophone", 80),
    STYLO_OCTAVE(20, InstrumentMode.PIANO, "Octave Buzz", "Lead with a growling octave-down layer", 87, "Stylophone"),
    STYLO_FIFTHS(20, InstrumentMode.PIANO, "Power Fifths", "Parallel fifths — instant riff machine", 86, "Stylophone"),
    STYLO_SOFT(20, InstrumentMode.PIANO, "Soft Breath Lead", "Breathy calliope-style stylus lead", 82, "Stylophone"),
    STYLO_CHIFF(20, InstrumentMode.PIANO, "Chiff Lead", "Percussive chiff-attack stylus lead", 83, "Stylophone"),
    STYLO_VOICE(20, InstrumentMode.PIANO, "Voice Lead", "Singing vocal-formant lead", 85, "Stylophone"),
    STYLO_HARMONICA(22, InstrumentMode.PIANO, "Mouth Organ Buzz", "Harmonica-style reedy melody", 22, "Stylophone"),
    STYLO_ACCORDION(22, InstrumentMode.PIANO, "Squeezebox Drone", "Accordion-style sustained drone", 21, "Stylophone"),
    STYLO_COMBO(22, InstrumentMode.PIANO, "60s Combo Buzz", "Thin transistor-organ stylus tone", 17, "Stylophone"),
    STYLO_DRONE_PIPES(22, InstrumentMode.PIANO, "Drone Pipes", "Bagpipe-style drone with chanter bite", 109, "Stylophone"),
    STYLO_THEREMIN(23, InstrumentMode.PIANO, "Theremin Whistle", "Eerie whistle — turn Slide on for the full effect", 78, "Stylophone"),
    STYLO_GAME(23, InstrumentMode.PIANO, "Retro Game Lead", "Chip-style ocarina blips", 79, "Stylophone"),
    STYLO_BRASS(20, InstrumentMode.PIANO, "Brass Buzz", "Fat synth-brass stylus stabs", 62, "Stylophone"),
    STYLO_BASS(20, InstrumentMode.PIANO, "Stylo Bass", "Round synth bass — pocket bassline machine", 38, "Stylophone"),
    STYLO_ACID_BASS(20, InstrumentMode.PIANO, "Acid Buzz Bass", "Squelchy resonant bass buzz", 39, "Stylophone"),
    STYLO_DRONE_BASS(20, InstrumentMode.PIANO, "Drone Bass", "Bass buzz under a sustained fifth drone", 38, "Stylophone", 86),
    STYLO_SCIFI(23, InstrumentMode.PIANO, "Sci-Fi Drone", "Bowed glassy drone — B-movie flying saucer", 92, "Stylophone"),
    STYLO_METALLIC(23, InstrumentMode.PIANO, "Metallic Drone", "Cold shimmering metallic drone", 93, "Stylophone"),
    STYLO_CHOIR_BUZZ(22, InstrumentMode.PIANO, "Haunted Choir", "Stylus melody sung by a ghostly choir", 54, "Stylophone", 52),

    GM_001(20, InstrumentMode.PIANO, "001 Acoustic Grand Piano", "General MIDI", 0, "GM Piano"),
    GM_002(20, InstrumentMode.PIANO, "002 Bright Acoustic Piano", "General MIDI", 1, "GM Piano"),
    GM_003(20, InstrumentMode.PIANO, "003 Electric Grand Piano", "General MIDI", 2, "GM Piano"),
    GM_004(20, InstrumentMode.PIANO, "004 Honky-tonk Piano", "General MIDI", 3, "GM Piano"),
    GM_005(20, InstrumentMode.PIANO, "005 Electric Piano 1", "General MIDI", 4, "GM Piano"),
    GM_006(20, InstrumentMode.PIANO, "006 Electric Piano 2", "General MIDI", 5, "GM Piano"),
    GM_007(20, InstrumentMode.PIANO, "007 Harpsichord", "General MIDI", 6, "GM Piano"),
    GM_008(20, InstrumentMode.PIANO, "008 Clavinet", "General MIDI", 7, "GM Piano"),
    GM_009(23, InstrumentMode.PIANO, "009 Celesta", "General MIDI", 8, "GM Chromatic"),
    GM_010(23, InstrumentMode.PIANO, "010 Glockenspiel", "General MIDI", 9, "GM Chromatic"),
    GM_011(23, InstrumentMode.PIANO, "011 Music Box", "General MIDI", 10, "GM Chromatic"),
    GM_012(23, InstrumentMode.PIANO, "012 Vibraphone", "General MIDI", 11, "GM Chromatic"),
    GM_013(23, InstrumentMode.PIANO, "013 Marimba", "General MIDI", 12, "GM Chromatic"),
    GM_014(23, InstrumentMode.PIANO, "014 Xylophone", "General MIDI", 13, "GM Chromatic"),
    GM_015(23, InstrumentMode.PIANO, "015 Tubular Bells", "General MIDI", 14, "GM Chromatic"),
    GM_016(23, InstrumentMode.PIANO, "016 Dulcimer", "General MIDI", 15, "GM Chromatic"),
    GM_017(22, InstrumentMode.PIANO, "017 Drawbar Organ", "General MIDI", 16, "GM Organ"),
    GM_018(22, InstrumentMode.PIANO, "018 Percussive Organ", "General MIDI", 17, "GM Organ"),
    GM_019(22, InstrumentMode.PIANO, "019 Rock Organ", "General MIDI", 18, "GM Organ"),
    GM_020(22, InstrumentMode.PIANO, "020 Church Organ", "General MIDI", 19, "GM Organ"),
    GM_021(22, InstrumentMode.PIANO, "021 Reed Organ", "General MIDI", 20, "GM Organ"),
    GM_022(22, InstrumentMode.PIANO, "022 Accordion", "General MIDI", 21, "GM Organ"),
    GM_023(22, InstrumentMode.PIANO, "023 Harmonica", "General MIDI", 22, "GM Organ"),
    GM_024(22, InstrumentMode.PIANO, "024 Tango Accordion", "General MIDI", 23, "GM Organ"),
    GM_025(21, InstrumentMode.PIANO, "025 Acoustic Guitar (nylon)", "General MIDI", 24, "GM Guitar"),
    GM_026(21, InstrumentMode.PIANO, "026 Acoustic Guitar (steel)", "General MIDI", 25, "GM Guitar"),
    GM_027(21, InstrumentMode.PIANO, "027 Electric Guitar (jazz)", "General MIDI", 26, "GM Guitar"),
    GM_028(21, InstrumentMode.PIANO, "028 Electric Guitar (clean)", "General MIDI", 27, "GM Guitar"),
    GM_029(21, InstrumentMode.PIANO, "029 Electric Guitar (muted)", "General MIDI", 28, "GM Guitar"),
    GM_030(21, InstrumentMode.PIANO, "030 Overdriven Guitar", "General MIDI", 29, "GM Guitar"),
    GM_031(21, InstrumentMode.PIANO, "031 Distortion Guitar", "General MIDI", 30, "GM Guitar"),
    GM_032(21, InstrumentMode.PIANO, "032 Guitar Harmonics", "General MIDI", 31, "GM Guitar"),
    GM_033(20, InstrumentMode.PIANO, "033 Acoustic Bass", "General MIDI", 32, "GM Bass"),
    GM_034(20, InstrumentMode.PIANO, "034 Electric Bass (finger)", "General MIDI", 33, "GM Bass"),
    GM_035(20, InstrumentMode.PIANO, "035 Electric Bass (pick)", "General MIDI", 34, "GM Bass"),
    GM_036(20, InstrumentMode.PIANO, "036 Fretless Bass", "General MIDI", 35, "GM Bass"),
    GM_037(20, InstrumentMode.PIANO, "037 Slap Bass 1", "General MIDI", 36, "GM Bass"),
    GM_038(20, InstrumentMode.PIANO, "038 Slap Bass 2", "General MIDI", 37, "GM Bass"),
    GM_039(20, InstrumentMode.PIANO, "039 Synth Bass 1", "General MIDI", 38, "GM Bass"),
    GM_040(20, InstrumentMode.PIANO, "040 Synth Bass 2", "General MIDI", 39, "GM Bass"),
    GM_041(21, InstrumentMode.PIANO, "041 Violin", "General MIDI", 40, "GM Strings"),
    GM_042(21, InstrumentMode.PIANO, "042 Viola", "General MIDI", 41, "GM Strings"),
    GM_043(21, InstrumentMode.PIANO, "043 Cello", "General MIDI", 42, "GM Strings"),
    GM_044(21, InstrumentMode.PIANO, "044 Contrabass", "General MIDI", 43, "GM Strings"),
    GM_045(21, InstrumentMode.PIANO, "045 Tremolo Strings", "General MIDI", 44, "GM Strings"),
    GM_046(21, InstrumentMode.PIANO, "046 Pizzicato Strings", "General MIDI", 45, "GM Strings"),
    GM_047(21, InstrumentMode.PIANO, "047 Orchestral Harp", "General MIDI", 46, "GM Strings"),
    GM_048(21, InstrumentMode.PIANO, "048 Timpani", "General MIDI", 47, "GM Strings"),
    GM_049(21, InstrumentMode.PIANO, "049 String Ensemble 1", "General MIDI", 48, "GM Ensemble"),
    GM_050(21, InstrumentMode.PIANO, "050 String Ensemble 2", "General MIDI", 49, "GM Ensemble"),
    GM_051(21, InstrumentMode.PIANO, "051 Synth Strings 1", "General MIDI", 50, "GM Ensemble"),
    GM_052(21, InstrumentMode.PIANO, "052 Synth Strings 2", "General MIDI", 51, "GM Ensemble"),
    GM_053(21, InstrumentMode.PIANO, "053 Choir Aahs", "General MIDI", 52, "GM Ensemble"),
    GM_054(21, InstrumentMode.PIANO, "054 Voice Oohs", "General MIDI", 53, "GM Ensemble"),
    GM_055(21, InstrumentMode.PIANO, "055 Synth Voice", "General MIDI", 54, "GM Ensemble"),
    GM_056(21, InstrumentMode.PIANO, "056 Orchestra Hit", "General MIDI", 55, "GM Ensemble"),
    GM_057(21, InstrumentMode.PIANO, "057 Trumpet", "General MIDI", 56, "GM Brass"),
    GM_058(21, InstrumentMode.PIANO, "058 Trombone", "General MIDI", 57, "GM Brass"),
    GM_059(21, InstrumentMode.PIANO, "059 Tuba", "General MIDI", 58, "GM Brass"),
    GM_060(21, InstrumentMode.PIANO, "060 Muted Trumpet", "General MIDI", 59, "GM Brass"),
    GM_061(21, InstrumentMode.PIANO, "061 French Horn", "General MIDI", 60, "GM Brass"),
    GM_062(21, InstrumentMode.PIANO, "062 Brass Section", "General MIDI", 61, "GM Brass"),
    GM_063(21, InstrumentMode.PIANO, "063 Synth Brass 1", "General MIDI", 62, "GM Brass"),
    GM_064(21, InstrumentMode.PIANO, "064 Synth Brass 2", "General MIDI", 63, "GM Brass"),
    GM_065(21, InstrumentMode.PIANO, "065 Soprano Sax", "General MIDI", 64, "GM Reed"),
    GM_066(21, InstrumentMode.PIANO, "066 Alto Sax", "General MIDI", 65, "GM Reed"),
    GM_067(21, InstrumentMode.PIANO, "067 Tenor Sax", "General MIDI", 66, "GM Reed"),
    GM_068(21, InstrumentMode.PIANO, "068 Baritone Sax", "General MIDI", 67, "GM Reed"),
    GM_069(21, InstrumentMode.PIANO, "069 Oboe", "General MIDI", 68, "GM Reed"),
    GM_070(21, InstrumentMode.PIANO, "070 English Horn", "General MIDI", 69, "GM Reed"),
    GM_071(21, InstrumentMode.PIANO, "071 Bassoon", "General MIDI", 70, "GM Reed"),
    GM_072(21, InstrumentMode.PIANO, "072 Clarinet", "General MIDI", 71, "GM Reed"),
    GM_073(21, InstrumentMode.PIANO, "073 Piccolo", "General MIDI", 72, "GM Pipe"),
    GM_074(21, InstrumentMode.PIANO, "074 Flute", "General MIDI", 73, "GM Pipe"),
    GM_075(21, InstrumentMode.PIANO, "075 Recorder", "General MIDI", 74, "GM Pipe"),
    GM_076(21, InstrumentMode.PIANO, "076 Pan Flute", "General MIDI", 75, "GM Pipe"),
    GM_077(21, InstrumentMode.PIANO, "077 Blown Bottle", "General MIDI", 76, "GM Pipe"),
    GM_078(21, InstrumentMode.PIANO, "078 Shakuhachi", "General MIDI", 77, "GM Pipe"),
    GM_079(21, InstrumentMode.PIANO, "079 Whistle", "General MIDI", 78, "GM Pipe"),
    GM_080(21, InstrumentMode.PIANO, "080 Ocarina", "General MIDI", 79, "GM Pipe"),
    GM_081(20, InstrumentMode.PIANO, "081 Lead 1 (square)", "General MIDI", 80, "GM Synth Lead"),
    GM_082(20, InstrumentMode.PIANO, "082 Lead 2 (sawtooth)", "General MIDI", 81, "GM Synth Lead"),
    GM_083(20, InstrumentMode.PIANO, "083 Lead 3 (calliope)", "General MIDI", 82, "GM Synth Lead"),
    GM_084(20, InstrumentMode.PIANO, "084 Lead 4 (chiff)", "General MIDI", 83, "GM Synth Lead"),
    GM_085(20, InstrumentMode.PIANO, "085 Lead 5 (charang)", "General MIDI", 84, "GM Synth Lead"),
    GM_086(20, InstrumentMode.PIANO, "086 Lead 6 (voice)", "General MIDI", 85, "GM Synth Lead"),
    GM_087(20, InstrumentMode.PIANO, "087 Lead 7 (fifths)", "General MIDI", 86, "GM Synth Lead"),
    GM_088(20, InstrumentMode.PIANO, "088 Lead 8 (bass + lead)", "General MIDI", 87, "GM Synth Lead"),
    GM_089(20, InstrumentMode.PIANO, "089 Pad 1 (new age)", "General MIDI", 88, "GM Synth Pad"),
    GM_090(20, InstrumentMode.PIANO, "090 Pad 2 (warm)", "General MIDI", 89, "GM Synth Pad"),
    GM_091(20, InstrumentMode.PIANO, "091 Pad 3 (polysynth)", "General MIDI", 90, "GM Synth Pad"),
    GM_092(20, InstrumentMode.PIANO, "092 Pad 4 (choir)", "General MIDI", 91, "GM Synth Pad"),
    GM_093(20, InstrumentMode.PIANO, "093 Pad 5 (bowed)", "General MIDI", 92, "GM Synth Pad"),
    GM_094(20, InstrumentMode.PIANO, "094 Pad 6 (metallic)", "General MIDI", 93, "GM Synth Pad"),
    GM_095(20, InstrumentMode.PIANO, "095 Pad 7 (halo)", "General MIDI", 94, "GM Synth Pad"),
    GM_096(20, InstrumentMode.PIANO, "096 Pad 8 (sweep)", "General MIDI", 95, "GM Synth Pad"),
    GM_097(23, InstrumentMode.PIANO, "097 FX 1 (rain)", "General MIDI", 96, "GM Synth FX"),
    GM_098(23, InstrumentMode.PIANO, "098 FX 2 (soundtrack)", "General MIDI", 97, "GM Synth FX"),
    GM_099(23, InstrumentMode.PIANO, "099 FX 3 (crystal)", "General MIDI", 98, "GM Synth FX"),
    GM_100(23, InstrumentMode.PIANO, "100 FX 4 (atmosphere)", "General MIDI", 99, "GM Synth FX"),
    GM_101(23, InstrumentMode.PIANO, "101 FX 5 (brightness)", "General MIDI", 100, "GM Synth FX"),
    GM_102(23, InstrumentMode.PIANO, "102 FX 6 (goblins)", "General MIDI", 101, "GM Synth FX"),
    GM_103(23, InstrumentMode.PIANO, "103 FX 7 (echoes)", "General MIDI", 102, "GM Synth FX"),
    GM_104(23, InstrumentMode.PIANO, "104 FX 8 (sci-fi)", "General MIDI", 103, "GM Synth FX"),
    GM_105(23, InstrumentMode.PIANO, "105 Sitar", "General MIDI", 104, "GM Ethnic"),
    GM_106(23, InstrumentMode.PIANO, "106 Banjo", "General MIDI", 105, "GM Ethnic"),
    GM_107(23, InstrumentMode.PIANO, "107 Shamisen", "General MIDI", 106, "GM Ethnic"),
    GM_108(23, InstrumentMode.PIANO, "108 Koto", "General MIDI", 107, "GM Ethnic"),
    GM_109(23, InstrumentMode.PIANO, "109 Kalimba", "General MIDI", 108, "GM Ethnic"),
    GM_110(23, InstrumentMode.PIANO, "110 Bag pipe", "General MIDI", 109, "GM Ethnic"),
    GM_111(23, InstrumentMode.PIANO, "111 Fiddle", "General MIDI", 110, "GM Ethnic"),
    GM_112(23, InstrumentMode.PIANO, "112 Shanai", "General MIDI", 111, "GM Ethnic"),
    GM_113(23, InstrumentMode.PIANO, "113 Tinkle Bell", "General MIDI", 112, "GM Percussive"),
    GM_114(23, InstrumentMode.PIANO, "114 Agogo", "General MIDI", 113, "GM Percussive"),
    GM_115(23, InstrumentMode.PIANO, "115 Steel Drums", "General MIDI", 114, "GM Percussive"),
    GM_116(23, InstrumentMode.PIANO, "116 Woodblock", "General MIDI", 115, "GM Percussive"),
    GM_117(23, InstrumentMode.PIANO, "117 Taiko Drum", "General MIDI", 116, "GM Percussive"),
    GM_118(23, InstrumentMode.PIANO, "118 Melodic Tom", "General MIDI", 117, "GM Percussive"),
    GM_119(23, InstrumentMode.PIANO, "119 Synth Drum", "General MIDI", 118, "GM Percussive"),
    GM_120(23, InstrumentMode.PIANO, "120 Reverse Cymbal", "General MIDI", 119, "GM Percussive"),
    GM_121(23, InstrumentMode.PIANO, "121 Guitar Fret Noise", "General MIDI", 120, "GM Sound FX"),
    GM_122(23, InstrumentMode.PIANO, "122 Breath Noise", "General MIDI", 121, "GM Sound FX"),
    GM_123(23, InstrumentMode.PIANO, "123 Seashore", "General MIDI", 122, "GM Sound FX"),
    GM_124(23, InstrumentMode.PIANO, "124 Bird Tweet", "General MIDI", 123, "GM Sound FX"),
    GM_125(23, InstrumentMode.PIANO, "125 Telephone Ring", "General MIDI", 124, "GM Sound FX"),
    GM_126(23, InstrumentMode.PIANO, "126 Helicopter", "General MIDI", 125, "GM Sound FX"),
    GM_127(23, InstrumentMode.PIANO, "127 Applause", "General MIDI", 126, "GM Sound FX"),
    GM_128(23, InstrumentMode.PIANO, "128 Gunshot", "General MIDI", 127, "GM Sound FX"),

    DRUM_ROCK1(0, InstrumentMode.DRUMS, "Rock 1", "Sampled big rock kit", 1600, "Genre Kits"),
    DRUM_ROCK2(0, InstrumentMode.DRUMS, "Rock 2", "Punchy studio kit", 16, "Genre Kits"),
    DRUM_ROCK3(0, InstrumentMode.DRUMS, "Rock 3", "Natural studio kit · roomy", 1300, "Genre Kits"),
    DRUM_METAL1(0, InstrumentMode.DRUMS, "Metal 1", "Driven rock kit · aggressive", 11600, "Genre Kits"),
    DRUM_METAL2(0, InstrumentMode.DRUMS, "Metal 2", "Driven sampled rock kit · heavy", 11700, "Genre Kits"),
    DRUM_POP(0, InstrumentMode.DRUMS, "Pop", "Studio kit · room", 8, "Genre Kits"),
    DRUM_FUNK(0, InstrumentMode.DRUMS, "Funk", "Sampled live kit · tight", 1400, "Genre Kits"),
    DRUM_GEN_JAZZ(0, InstrumentMode.DRUMS, "Jazz", "Light jazz kit", 32, "Genre Kits"),
    DRUM_LOFI(0, InstrumentMode.DRUMS, "Lo-Fi", "Vintage boom-bap kit", 25, "Genre Kits"),
    DRUM_HIPHOP(0, InstrumentMode.DRUMS, "Hip-Hop", "Sampled analog beatbox · boom-bap", 1100, "Genre Kits"),
    DRUM_DISCO(0, InstrumentMode.DRUMS, "Disco", "Studio kit · big hall", 0, "Genre Kits"),
    DRUM_HOUSE(0, InstrumentMode.DRUMS, "House / DJ", "Sampled dance machine", 1200, "Genre Kits"),
    DRUM_TECHNO(0, InstrumentMode.DRUMS, "Techno", "Sampled techno machine · alt", 2001, "Genre Kits"),
    DRUM_REGGAE(0, InstrumentMode.DRUMS, "Reggae", "Real reggae kit · roomy roots samples", 3200, "Genre Kits"),
    DRUM_REGGAE_ONEDROP(0, InstrumentMode.DRUMS, "Reggae One-Drop", "Cross-stick leads · snare pad = side stick, rim = full skin", 3200, "Genre Kits"),
    DRUM_MAMBO(0, InstrumentMode.DRUMS, "Mambo", "Latin section · congas, timbales, cowbell", 0, "Genre Kits"),
    DRUM_BEATBOX(0, InstrumentMode.DRUMS, "Beatbox", "Roland CR-78 · 808/909 drum machine", 3300, "Genre Kits"),
    DRUM_JUNGLE(0, InstrumentMode.DRUMS, "Jungle", "Chopped breakbeat machine", 3400, "Genre Kits"),
    DRUM_TRAP(0, InstrumentMode.DRUMS, "Trap", "808 trap kit · booming sub", 3500, "Genre Kits"),
    DRUM_REGGAETON(0, InstrumentMode.DRUMS, "Reggaeton", "Dembow kit · Latin urban", 3600, "Genre Kits"),
    DRUM_DJENT(0, InstrumentMode.DRUMS, "Djent", "Modern metal · tight & gated", 4100, "Genre Kits"),
    DRUM_SLAM(0, InstrumentMode.DRUMS, "Slam", "Huge gated arena kit", 4300, "Genre Kits"),

    DRUM_808(0, InstrumentMode.DRUMS, "808 Beats", "Sampled analog beatbox", 1100, "Drum Machines (HQ)"),
    DRUM_808_BOOM(0, InstrumentMode.DRUMS, "808 Boom", "Analog beatbox · deep", 1102, "Drum Machines (HQ)"),
    DRUM_808_PUNCH(0, InstrumentMode.DRUMS, "808 Punch", "Analog beatbox · tight", 1104, "Drum Machines (HQ)"),
    DRUM_909(0, InstrumentMode.DRUMS, "909 Beats", "Sampled dance machine drums", 1200, "Drum Machines (HQ)"),
    DRUM_PHAT(0, InstrumentMode.DRUMS, "Phat Machine", "Sampled fat electronic kit", 1500, "Drum Machines (HQ)"),
    DRUM_LINN(0, InstrumentMode.DRUMS, "80s Drum Computer", "Sampled 80s drum computer", 1800, "Drum Machines (HQ)"),
    DRUM_R8(0, InstrumentMode.DRUMS, "Digital Kit 88", "Sampled digital drum machine", 1900, "Drum Machines (HQ)"),
    DRUM_R8_2(0, InstrumentMode.DRUMS, "Digital Kit 88 · Set 2", "Sampled digital drum machine · alt", 1901, "Drum Machines (HQ)"),
    DRUM_MAGIC_TECHNO(0, InstrumentMode.DRUMS, "Magic Techno", "Sampled techno machine", 2000, "Drum Machines (HQ)"),
    DRUM_TR707(0, InstrumentMode.DRUMS, "TR-707", "Classic 80s drum machine", 3700, "Drum Machines (HQ)"),
    DRUM_TR606(0, InstrumentMode.DRUMS, "TR-606", "Drumatix analog machine", 3800, "Drum Machines (HQ)"),
    DRUM_SIMMONS(0, InstrumentMode.DRUMS, "Simmons", "80s electronic drums · synth toms", 3900, "Drum Machines (HQ)"),
    DRUM_ELECTRO(0, InstrumentMode.DRUMS, "Electro", "Electro-funk machine kit", 4000, "Drum Machines (HQ)"),
    DRUM_DANCE(0, InstrumentMode.DRUMS, "Dance", "Modern dance machine", 4200, "Drum Machines (HQ)"),
    DRUM_SNES(0, InstrumentMode.DRUMS, "SNES", "16-bit chiptune drum kit", 4400, "Drum Machines (HQ)"),

    DRUM_GIANT_STUDIO(0, InstrumentMode.DRUMS, "Giant Studio Kit", "Large multi-sampled studio kit", 2100, "Expanded Drum Kits"),
    DRUM_HARD_ROCK_CLASSIC(0, InstrumentMode.DRUMS, "Hard Rock Classic", "Original hard rock acoustic kit", 2200, "Expanded Drum Kits"),
    DRUM_HARD_ROCK_V3(0, InstrumentMode.DRUMS, "Hard Rock V3", "Updated hard rock acoustic kit", 2300, "Expanded Drum Kits"),
    DRUM_MELOTTI_STUDIO(0, InstrumentMode.DRUMS, "Melotti Studio", "Studio acoustic drum collection", 2400, "Expanded Drum Kits"),
    DRUM_REAL_ACOUSTIC_5(0, InstrumentMode.DRUMS, "Real Acoustic 5", "Multi-layer acoustic drum kit", 2500, "Expanded Drum Kits"),
    DRUM_ROLAND_CANVAS(0, InstrumentMode.DRUMS, "Roland Canvas Standard", "Sound Canvas GM standard kit", 2600, "Expanded Drum Kits"),
    DRUM_CHARLIE_STANDARD(0, InstrumentMode.DRUMS, "Charlie Standard", "Modified GM standard kit", 2700, "Expanded Drum Kits"),
    DRUM_TAMA_ROCKSTAR_CLASSIC(0, InstrumentMode.DRUMS, "Tama RockStar Classic", "Original RockStar sampled kit", 2800, "Expanded Drum Kits"),
    DRUM_TAMA_ROCKSTAR_2(0, InstrumentMode.DRUMS, "Tama RockStar 2", "Expanded RockStar sampled kit", 2900, "Expanded Drum Kits"),
    DRUM_ULTIMATE_CM(0, InstrumentMode.DRUMS, "Ultimate CM Kit", "Classic GM and CM drum kit", 3000, "Expanded Drum Kits"),
    DRUM_CONGAS(0, InstrumentMode.DRUMS, "Latin Congas", "MEINL congas & tumbas · real samples", 3100, "Expanded Drum Kits"),
    DRUM_FUNK2(0, InstrumentMode.DRUMS, "Funk Studio", "GS funk kit · tight & dry", 4500, "Expanded Drum Kits"),
    DRUM_POP2(0, InstrumentMode.DRUMS, "Pop Studio", "GS pop kit · clean", 4600, "Expanded Drum Kits"),
    DRUM_METAL3(0, InstrumentMode.DRUMS, "Metal Studio", "GS metal kit · aggressive", 4700, "Expanded Drum Kits"),
    DRUM_JAZZ2(0, InstrumentMode.DRUMS, "Jazz Club", "GS jazz kit · warm ride", 4800, "Expanded Drum Kits"),
    DRUM_BRUSH2(0, InstrumentMode.DRUMS, "Brush Studio", "GS brush kit · soft sweeps", 4900, "Expanded Drum Kits"),

    DRUM_STANDARD(0, InstrumentMode.DRUMS, "Standard", "GeneralUser GS · dry, neutral", 0, "Classic GM Kits"),
    DRUM_ROOM(0, InstrumentMode.DRUMS, "Room", "GeneralUser GS · roomy ambience", 8, "Classic GM Kits"),
    DRUM_POWER(0, InstrumentMode.DRUMS, "Power", "GeneralUser GS · big & punchy", 16, "Classic GM Kits"),
    DRUM_ELECTRONIC(0, InstrumentMode.DRUMS, "Electronic", "GeneralUser GS · synth kit", 24, "Classic GM Kits"),
    DRUM_BRUSH(0, InstrumentMode.DRUMS, "Brush", "GeneralUser GS · brushes", 40, "Classic GM Kits");


    final int nativeId;
    final InstrumentMode mode;
    final String label;
    final String detail;
    final int program;
    final String category;
    final String asset;   // lazy-loaded HQ soundfont (piano library); null otherwise
    final int layer;      // second GM program layered on every note; -1 = none

    TonePreset(int nativeId, InstrumentMode mode, String label, String detail) {
        this(nativeId, mode, label, detail, -1, "", null, -1);
    }

    TonePreset(int nativeId, InstrumentMode mode, String label, String detail, int program, String category) {
        this(nativeId, mode, label, detail, program, category, null, -1);
    }

    TonePreset(int nativeId, InstrumentMode mode, String label, String detail, int program, String category, String asset) {
        this(nativeId, mode, label, detail, program, category, asset, -1);
    }

    TonePreset(int nativeId, InstrumentMode mode, String label, String detail, int program, String category, int layer) {
        this(nativeId, mode, label, detail, program, category, null, layer);
    }

    TonePreset(int nativeId, InstrumentMode mode, String label, String detail, int program, String category, String asset, int layer) {
        this.nativeId = nativeId;
        this.mode = mode;
        this.label = label;
        this.detail = detail;
        this.program = program;
        this.category = category;
        this.asset = asset;
        this.layer = layer;
    }

    String displayText() {
        return label + "\n" + detail;
    }

    static TonePreset defaultFor(InstrumentMode mode) {
        switch (mode) {
            case BASS:
                return BASS_SANSAMP;
            case PIANO:
                return STEINWAY_LIB;   // flagship sampled 9-foot grand (lazy slot 4)
            case DRUMS:
                return DRUM_ROCK1;
            case ELECTRIC_GUITAR:
            default:
                return GUITAR_TS9;
        }
    }

    static TonePreset[] forMode(InstrumentMode mode) {
        int count = 0;
        for (TonePreset preset : values()) {
            if (preset.mode == mode) {
                count++;
            }
        }

        TonePreset[] presets = new TonePreset[count];
        int index = 0;
        for (TonePreset preset : values()) {
            if (preset.mode == mode) {
                presets[index++] = preset;
            }
        }
        return presets;
    }
}
